services:
  usos-sync:
    container_name: usos-sync
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.json:/usr/src/app/config.json:rw
    command: ["node", "dist/main.js"]
